parameters:

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nines\SolrBundle\:
    resource: '../../'
    exclude: '../../{DependencyInjection,Entity,Resources,Tests}'
