parameters:

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nines\SolrBundle\:
    resource: '../../'
    exclude: '../../{DependencyInjection,Entity,Resources,Tests}'

  Nines\SolrBundle\DataCollector\RequestCollector:
    tags:
      - { name: data_collector, template: '@NinesSolr/collector/toolbar.html.twig', id: 'solr.request_collector' }

  Nines\SolrBundle\Client\ClientFactory: ~

  Solarium\Client:
    factory: [ '@Nines\SolrBundle\Client\ClientFactory', 'build' ]

  Nines\SolrBundle\Mapper\EntityMapperFactory:
    arguments: [ '%kernel.environment%' ]

  Nines\SolrBundle\Mapper\EntityMapper:
    factory: [ '@Nines\SolrBundle\Mapper\EntityMapperFactory', 'build' ]
