nines_user_security:
  type: attribute
  prefix: /
  resource: '@NinesUserBundle/Controller/SecurityController.php'

nines_user_profile:
  type: attribute
  prefix: /profile
  resource: '@NinesUserBundle/Controller/ProfileController.php'

nines_user_admin:
  type: attribute
  prefix: /admin/user
  resource: '@NinesUserBundle/Controller/AdminController.php'
