<?php

declare(strict_types=1);

namespace Nines\MediaBundle\Tests\Repository;

use Nines\MediaBundle\Repository\ImageRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class ImageRepositoryTest extends ServiceTestCase {
    private ?ImageRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(ImageRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(10, $this->repo->indexQuery()->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(2, $this->repo->searchQuery('30191231240_4010f114ba_c')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(ImageRepository::class);
    }
}
