<?php

declare(strict_types=1);

namespace Nines\MediaBundle\Tests\Repository;

use Nines\MediaBundle\Repository\LinkRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class LinkRepositoryTest extends ServiceTestCase {
    private ?LinkRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(LinkRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(10, $this->repo->indexQuery()->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(10, $this->repo->searchQuery('example.com')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(LinkRepository::class);
    }
}
