<?php

declare(strict_types=1);

namespace Nines\MediaBundle\Tests\Repository;

use Nines\MediaBundle\Repository\PdfRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class PdfRepositoryTest extends ServiceTestCase {
    private ?PdfRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(PdfRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(10, $this->repo->indexQuery()->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(2, $this->repo->searchQuery('holmes_4')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(PdfRepository::class);
    }
}
