services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nines\UtilBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources,Tests}'

    Nines\UtilBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments', 'knp_paginator.injectable']

    Nines\UtilBundle\EventListener\ContentExcerptListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Nines\UtilBundle\EventListener\TermNameListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Nines\UtilBundle\Services\Text:
        arguments:
            $defaultTrimLength: ~

    Nines\UtilBundle\Twig\TextExtension:
        tags:
            - { name : twig.extension }

    Nines\UtilBundle\Services\ContributionManager:
        tags:
            - { name: 'doctrine.event_subscriber' }

    Nines\UtilBundle\Services\LinkManager:
        arguments:
            $routing: '%nines_util.routing%'
        tags:
            - { name: 'doctrine.event_subscriber' }

    Nines\UtilBundle\Services\ReferenceManager:
        arguments:
            $routing: '%nines_util.routing%'
        tags:
            - { name: 'doctrine.event_subscriber' }
