<?php

declare(strict_types=1);

namespace Nines\FeedbackBundle\Tests\Repository;

use Nines\FeedbackBundle\Repository\CommentNoteRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class CommentNoteRepositoryTest extends ServiceTestCase {
    private ?CommentNoteRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(CommentNoteRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(5, $this->repo->indexQuery()->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(5, $this->repo->searchQuery('paragraph')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(CommentNoteRepository::class);
    }
}
