<?php

declare(strict_types=1);

namespace Nines\SolrBundle\Tests\Command;

use Nines\SolrBundle\Services\SolrManager;
use Nines\SolrBundle\TestUtil\ClientTestTrait;
use Nines\UtilBundle\TestCase\CommandTestCase;

class PingCommandTest extends CommandTestCase {
    use ClientTestTrait;

    private ?SolrManager $manager = null;

    public function testExecute() : void {
        $this->addResponse([
            'responseHeader' => [
                'status' => '0',
                'QTime' => '2123.132',
            ],
        ]);
        $client = $this->mockClient();
        $this->manager->setClient($client);

        $output = $this->execute('nines:solr:ping');
        $this->assertStringContainsString('Ping: 2123.132ms', $output);
    }

    public function testFail() : void {
        $this->addResponse('Unknown error', 500);
        $client = $this->mockClient();
        $this->manager->setClient($client);

        $output = $this->execute('nines:solr:ping');
        $this->assertStringStartsWith('Ping failed: Solr HTTP error', $output);
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->manager = static::getContainer()->get(SolrManager::class);
    }
}
