<?php

declare(strict_types=1);

namespace Nines\SolrBundle\Tests\Client;

use Nines\SolrBundle\Client\LoggerPlugin;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class LoggerPluginTest extends ServiceTestCase {
    private ?LoggerPlugin $plugin = null;

    public function testSetup() : void {
        $this->assertInstanceOf(LoggerPlugin::class, $this->plugin);
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->plugin = static::getContainer()->get(LoggerPlugin::class);
    }
}
