<?php

declare(strict_types=1);

namespace Nines\UserBundle\Tests\Command;

use Nines\UserBundle\Repository\UserRepository;
use Nines\UtilBundle\TestCase\CommandTestCase;

class DeactivateUserCommandTest extends CommandTestCase {
    private ?UserRepository $repo = null;

    public function testExecute() : void {
        $output = $this->execute('nines:user:deactivate', [
            'email' => 'user@example.com',
        ]);

        $this->assertSame("Account user@example.com is not active.\n", $output);
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->assertFalse($user->isActive());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(UserRepository::class);
    }
}
