<?php

declare(strict_types=1);

namespace Nines\UserBundle\Tests\Command;

use Nines\UserBundle\Repository\UserRepository;
use Nines\UserBundle\Services\UserManager;
use Nines\UtilBundle\TestCase\CommandTestCase;

class DemoteUserCommandTest extends CommandTestCase {
    private ?UserRepository $repo = null;

    private ?UserManager $manager = null;

    public function testExecute() : void {
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->manager->promote($user, 'a');

        $output = $this->execute('nines:user:demote', [
            'email' => 'user@example.com',
            'role' => 'a',
        ]);

        $this->assertSame("Role a removed from Unprivileged user.\n", $output);
        $this->em->clear();
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->assertFalse($user->hasRole('a'));
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(UserRepository::class);
        $this->manager = static::getContainer()->get(UserManager::class);
    }
}
