<?php

declare(strict_types=1);

namespace Nines\UserBundle\Tests\Command;

use Nines\UserBundle\Repository\UserRepository;
use Nines\UtilBundle\TestCase\CommandTestCase;

class PromoteUserCommandTest extends CommandTestCase {
    private ?UserRepository $repo = null;

    public function testExecute() : void {
        $output = $this->execute('nines:user:promote', [
            'email' => 'user@example.com',
            'role' => 'a',
        ]);

        $this->assertSame("Role a added to user user@example.com.\n", $output);
        $this->em->clear();
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->assertTrue($user->hasRole('a'));
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(UserRepository::class);
    }
}
