<?php

declare(strict_types=1);

namespace Nines\UserBundle\Tests\Command;

use Nines\UserBundle\Repository\UserRepository;
use Nines\UtilBundle\TestCase\CommandTestCase;

class ResetPasswordCommandTest extends CommandTestCase {
    private ?UserRepository $repo = null;

    public function testExecute() : void {
        $output = $this->execute('nines:user:reset', [
            'email' => 'user@example.com',
        ]);

        $this->assertSame("Password reset email sent to user@example.com.\n", $output);
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->assertNotNull($user->getResetToken());
        $this->assertNotNull($user->getResetExpiry());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = static::getContainer()->get(UserRepository::class);
    }
}
