parameters:
    nines_blog.excerpt_length: 100
    nines_blog.homepage_posts: 3
    nines_blog.menu_posts: 5

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nines\BlogBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Resources,Tests}'

    Nines\BlogBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags:
            - 'controller.service_arguments'
            - 'knp_paginator.injectable'

    Nines\BlogBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: postNavMenu, alias: nines_blog_posts}
            - { name: knp_menu.menu_builder, method: pageNavMenu, alias: nines_blog_pages}
